name: Form para criação de uma nova issue de feature!
description: Use este formulário para criar uma nova tarefa de forma mais simples. 🥳
projects: ["impulse5/i-mart"]
title: "🚀 Feature | "
body:
  - type: markdown
    attributes:
      value: |
        Preencha o formulário abaixo para criar uma nova tarefa de feature! 🚀
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
