name: Form para criação de uma nova issue de feature!
description: Use este formulário para criar uma nova tarefa de forma mais simples. 🥳
projects: ["impulse5/2"]
title: "🚀 Feature | "
body:
  - type: markdown
    attributes:
      value: |
        Preencha o formulário abaixo para criar uma nova tarefa de feature! 🚀
  - type: input
    id: description
    attributes:
      label: Descrição
      description: Descreva aqui sobre esta feature 🤔 *Coloque entre underlines
      placeholder: _Criar um novo botão..._
      value: _Coloque entre underlines._
    validations:
      required: true
  - type: input
    id: dependencies
    attributes:
      label: Dependências
      description: Quais são as dependências desta feature? 📦 Coloque da seguinte forma = - [ ] #numero da issue
      value: "- [ ] #1"
    validations:
      required: false
  
